const routes = {
  home: "/",
  order: "/order",
  search: "/search",
  active: "/active",
  support: "/support",
  source: "/source",
  forgotPassword: "/forgot-password",
  cart: "/cart",
  courseDetail: "/course-detail",
  me: "/me",
  myClass: "/my-class",
  profile: "/profile",
  balance: "/balance",
  orderHistory: "/order-history",
  myRecommend: "/my-recommend",
  userPayment: "/user/payment",
  withdrawal: "/withdrawal",
  withdrawalHistory: "/withdrawal-history",
  categories: "/categories",
  coming: "/coming",
  trending: "/trending",
  login: "/login",
  register: "/register",
  paymentBanking: "/payment-banking",
  learning: "/learning",
};

export default routes;
