const REGISTER = "REGISTER";
const LOGIN = "LOGIN";
const GET_USER_BY_ID = "GET_USER_BY_ID";
const GET_USER_ENTITY_FORGOT_PASSWORD = "GET_USER_ENTITY_FORGOT_PASSWORD";
const CHANGE_PASSWORD = "CHANGE_PASSWORD";

export {
    REGISTER,
    LOGIN,
    GET_USER_BY_ID,
    GET_USER_ENTITY_FORGOT_PASSWORD,
    CHANGE_PASSWORD
}